optimizer: CD
stopcondition {
  all_processed: false
  steps: 100000
}
train: true
batchsize: 100
data_proto: "D:\\test\\MNIST\\mnist.pbtxt"
eval_after: 1000
checkpoint_after: 10000
checkpoint_directory: "D:\\test\\outputRBM"
randomize: true
show_after: 1000
